spring.application.name=SmileCorp
# spring.datasource.url=jdbc:postgresql://ep-fragrant-dust-acft3x3r-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require
# spring.datasource.username=neondb_owner
# spring.datasource.password=npg_S7EkjWL1GcqV
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true